### ISSUE TITLE
Missing packages as part of molsim setup

### ISSUE THREAD

**Issue by bmcguir2** [bmcguir2/molsim#52]
Missing:

ruamel.yaml
tabulate
emcee
loguru
lmfit

**Comment by laserkelvin** [comment]
Weird, because they're in `setup.py`

https://github.com/bmcguir2/molsim/blob/b61108bdf5fd21a60d8b1a4b1910a7c73e1c13d0/setup.py#L22

**Comment by bmcguir2** [comment]
I did:

conda env create -f conda.yml molsim

then

pip install -e .

then

python -m ipykernel install --user --name molsim --display-name "molsim"

**Comment by laserkelvin** [comment]
Did you activate the environment between the `pip instal`l and `conda env create`?

My instructions skipped that, and that might be the reason why

**Comment by bmcguir2** [comment]
I don't believe I did!

**Comment by laserkelvin** [comment]
I'll update the instructions :)

**Comment by laserkelvin** [comment]
Updated the instructions, which hopefully should mean people won't have this issue. Closing it for now since there's nothing actionable left
