### ISSUE TITLE
Possible systematic offset from Gaussian normalization

### ISSUE THREAD

**Issue by keflavich** [bmcguir2/molsim#65]
I'm trying to benchmark pyspeckit against molsim and XCLASS.  I've made some progress, but I've found a systematic offset in the computed optical depths between XCLASS/pyseckit and molsim; the former are lower by a factor 1.064467, which is the ratio (2 pi / (8 log 2))^0.5 - i.e., the ratio of the normalization of the Gaussian integral to the FWMH/sigma ratio.

I think this indicates an error in molsim, but I'd like eyes on it.

The Gaussian line is here, and does not include any leading normalization factor:
https://github.com/bmcguir2/molsim/blob/master/molsim/utils.py#L69-L70

The tau calculation is here, and it's a lot harder to pin down exactly whether something could be missing:
https://github.com/bmcguir2/molsim/blob/master/molsim/classes.py#L1232-L1240
but I suspect `self.source.dV` is a FWHM and should be a `sigma` to be correct.

My derived tau in pyspeckit is also systematically different by a factor of v/c, but I believe this is a simple definitional choice; I calculate tau_nu, molsim calculates tau_v, so the systematic difference is expected.

The benchmarking notebook is here:
https://github.com/pyspeckit/pyspeckit-tests/blob/ce0aa614ef78d89db2f1f1b2767095ed1170f83c/xclass-benchmark/CO_Benchmark.ipynb

**Comment by keflavich** [comment]
For github cross-referencing purposes, [here](https://github.com/pyspeckit/pyspeckit-tests/pull/29) is the benchmark PR, and [here](https://github.com/pyspeckit/pyspeckit/pull/359) is the functionality being added into pyspeckit.

The jplspec module of astroquery (https://astroquery.readthedocs.io/en/latest/jplspec/jplspec.html) has been helpful here, and there's also a CDMS module soon (https://github.com/astropy/astroquery/pull/2143)

**Comment by bmcguir2** [comment]
@cixue maybe you can take a look?  I feel like I remember you digging around regarding a factor like this a while back - I don't recall what you discovered.

**Comment by cixue** [comment]
I agree and believe that the factor found to make the difference is from Gaussian normalization. 

As shown in Ref [https://www.cv.nrao.edu/~sransom/web/Ch7.html#E137](url), the peak optical depth has a factor of (ln2)^0.5 / (4 * pi^3/2), but [https://github.com/bmcguir2/molsim/blob/master/molsim/classes.py#L1232-L1240](url) uses 1/(8*pi). I can submit a pull request to fix the issue. 

@bmcguir2 I am not sure if the intention of the `_calc_tau` function is to have the peak value of tau or integrated value of it. If it is the former, we can correct the coefficent in the `_calc_tau` function.
